# Generated by Django 3.1.4 on 2020-12-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20201216_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
